name: Exemplo de fluxo de trabalho

on: 
  push:
    branches: [main]

jobs:
  acao_inicial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime OLA
        run: echo "Ola"
      - name: Imprime Tchau
        run: echo "Tchau"
    
